language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: "D++xwI7K1xobbhYr75n7ebGt1ODOoX5yPkkiryimUmFa+AumbvDhET6oVXVKYOl2kFOHfUtk22wg49JVr5NL4Ol+JIUfR8M/lfdFjEhtdUbl+SlZgBI6lT5nsBVdm/+1D3qbO27xpA5kzhyreoUUeGO6Oih4DX+ttMKySCw3l40="
  - secure: "KYsbzRt4iHzKd0Ehh3k3hxf95tX2fy8KM3EA85o5TQW7DYSTErSXsdxGUgvEZ57a1aEdRkiy+/xt0XVPzwVlLGP1EuKUjG8una7cm2uuVcRjKNSr11OU2E7mrQi76tLDU+XphwaBblWq8Yi1vGeffQAcQEBKn2CBzBwTmZH6Lcg="
  - secure: "XtmUvTRB3O7gZpbe8oPsgruC4awjOrT80Gus4OtpTEU7+8hIw66UsM0Qctp5WoYLqfg/RBVEOtmIF43ONzi3xe44wI27/Ztq4thJrqlUvERYlFfgosgsLmAnEMlfN6918Oq6o/4E1J1SwCUDTeP4TKavj0FGCHOTtbCZkG9orIE="
before_install:
  - npm install -g npm@~1.4.6
  - npm install -g grunt-cli
after_success:
  - npm run build
  - bash test/post_install.sh
